name: Run tests and lint

on: ['push', 'pull_request']

jobs:
  test-with-uv:
    name: python
    runs-on: ubuntu-latest

    steps:
      - name: Install de_DE.utf8 locale
        run: sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen de_DE.utf8

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.8"

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run ./test
